import Head from 'next/head'
import Header from '@components/Header'
import Footer from '@components/Footer'
import LandingPage from './home';

import { getCookie } from 'cookies-next';
import { useEffect } from 'react';
import { useRouter } from "next/router";


export default function Home(props) {
  const router = useRouter();
  useEffect(()=>{
    const user = getCookie('user');
    if(!user) {
      router.push('/home');
    } else {
      router.push('/dashboard');
    }
  });
  return (
  
    <div className="container">
        <Head>
        <title>Blind Guru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
      </Head>
      <main>
      </main>
      <Footer/>
    </div>
  )
}
